version: '3.9'

services:
  db:
    image: postgis/postgis
    environment:
      - POSTGRES_DB=testgis
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    networks:
      - net
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 127.0.0.1:8000:8000
    environment:
      - POSTGRES_DB=testgis
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db
    networks:
      - net

networks:
  net:
    driver: bridge

